# Project information

site_name: 'AWS Identity: Using Cognito for serverless consumer apps'
site_short_name: 'Using Cognito for serverless consumer apps'
site_description: 'In this workshop, you learn how to build a serverless customer-facing microservices application demonstrating end-to-end authentication and authorization using Amazon Cognito, Amazon API Gateway, AWS Lambda, and all things AWS Identity and Access Management (IAM). You have the opportunity to build an end-to-end functional app with a secure identity provider showcasing user authentication patterns.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://serverless-idm.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/amazon-cognito-identity-management-workshop'
repo_url: 'https://github.com/aws-samples/amazon-cognito-identity-management-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - '<i>Module 0</i>: Environment setup': '00-env-setup.md'
  - '<i>Module 1</i>: User signup and authentication': '01-user-auth.md'
  - '<i>Module 2</i>: Backend authorization with Amazon API Gateway': '02-backend-auth.md'
  - '<i>Module 3</i>: Retrieving and using temporary AWS credentials': '03-iam-auth.md'
  - '<i>Module 4</i>: Clean up': '04-clean-up.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'